name: blaze_flutter_sdk
description: "Flutter SDK for Blaze - Sports content widgets and player integration"
version: 0.1.1
publish_to: "none"
homepage: https://github.com/WSC-Sports/BlazeSDK-Flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: "^2.0.0"
  freezed_annotation: "^2.0.0"
  json_annotation: "^4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.4.7
  json_serializable: ^6.8.0

flutter:
  plugin:
    platforms:
      android:
        package: com.blaze.flutterblazesdk
        pluginClass: BlazeFlutterSdkPlugin
      ios:
        pluginClass: BlazeFlutterSdkPlugin
